# Generated by Django 5.1.6 on 2025-06-05 07:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htg_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('usd_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('btg_balance', models.DecimalField(decimal_places=8, default=0.0, max_digits=18)),
                ('btc_balance', models.DecimalField(decimal_places=8, default=0.0, max_digits=18)),
                ('usdt_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='FundTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_transfer_id', models.CharField(blank=True, max_length=9)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('HTG', 'HTG'), ('USD', 'USD'), ('BTG', 'BTG'), ('BTC', 'BTC'), ('USDT', 'USDT')], max_length=5)),
                ('method', models.CharField(choices=[('mobile', 'Mobile Money'), ('card', 'Kat Labank'), ('crypto', 'Kripto'), ('bank', 'Bank')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Annatant'), ('Completed', 'Reyisi'), ('Failed', 'Echwe')], default='Pending', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('HTG', 'HTG'), ('USD', 'USD'), ('BTG', 'BTG'), ('BTC', 'BTC'), ('USDT', 'USDT')], max_length=5)),
                ('payment_type', models.CharField(choices=[('renewal', 'Renouvle Dokiman'), ('fine', 'Pèman Kontravansyon')], db_index=True, max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('HTG', 'HTG'), ('USD', 'USD'), ('BTG', 'BTG'), ('BTC', 'BTC'), ('USDT', 'USDT')], max_length=5)),
                ('method', models.CharField(choices=[('mobile', 'Mobile Money'), ('card', 'Kat Labank'), ('crypto', 'Kripto'), ('bank', 'Bank')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Annatant'), ('Completed', 'Reyisi'), ('Failed', 'Echwe')], default='Pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('HTG', 'HTG'), ('USD', 'USD'), ('BTG', 'BTG'), ('BTC', 'BTC'), ('USDT', 'USDT')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Annatant'), ('Completed', 'Reyisi'), ('Failed', 'Echwe')], default='Pending', max_length=20)),
                ('reference', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=42, unique=True)),
                ('network', models.CharField(choices=[('bsc', 'Binance Smart Chain'), ('eth', 'Ethereum'), ('polygon', 'Polygon')], max_length=30)),
                ('wallet_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
            ],
        ),
    ]
