# Generated by Django 5.2.3 on 2026-02-02 20:10

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Réussi'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30)),
                ('currency', models.CharField(max_length=10)),
                ('method', models.CharField(choices=[('crypto', 'Crypto'), ('mobile', 'Mobile Money'), ('bank', 'Banque')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='HTG', max_length=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Réussi'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('method', models.CharField(choices=[('crypto', 'Crypto'), ('mobile', 'Mobile Money'), ('bank', 'Banque')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30)),
                ('currency', models.CharField(max_length=10)),
                ('provider', models.CharField(max_length=50)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('method', models.CharField(choices=[('crypto', 'Crypto'), ('mobile', 'Mobile Money'), ('bank', 'Banque')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Réussie'), ('failed', 'Échouée')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30)),
                ('currency', models.CharField(max_length=10)),
                ('tx_type', models.CharField(choices=[('CREDIT', 'Crédit'), ('DEBIT', 'Débit')], max_length=10)),
                ('transaction_type', models.CharField(choices=[('signup', 'Création de compte'), ('referral', 'Parrainage'), ('payment', 'Paiement'), ('bonus', 'Bonus'), ('daily_login', 'Bonus quotidien'), ('contract', 'Contrat'), ('transfer', 'Transfert'), ('alert', 'Alerte'), ('reminder', 'Rappel')], max_length=30)),
                ('source', models.CharField(choices=[('SYSTEM', 'Système'), ('USER', 'Utilisateur'), ('ADMIN', 'Administrateur')], default='USER', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Réussi'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_type', models.CharField(choices=[('crypto', 'Crypto'), ('mobile', 'Mobile Money'), ('bank', 'Banque')], max_length=20)),
                ('network', models.CharField(choices=[('btc', 'Bitcoin'), ('eth', 'Ethereum'), ('bsc', 'Binance Smart Chain')], max_length=50)),
                ('public_key', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=10)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
