# Generated by Django 5.2.3 on 2026-02-04 03:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_wallet_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tx_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bonus_type',
            field=models.CharField(choices=[('signup', 'Création de compte'), ('referral', 'Parrainage'), ('payment', 'Paiement'), ('random', 'Aléatoire'), ('daily_login', 'Bonus quotidien'), ('contract', 'Contrat'), ('transfer', 'Transfert'), ('alert', 'Alerte'), ('reminder', 'Rappel')], default='signup', max_length=30),
        ),
        migrations.AlterField(
            model_name='balancecurrency',
            name='currency',
            field=models.CharField(default='HTG', max_length=10),
        ),
        migrations.AlterField(
            model_name='fundtransfer',
            name='currency',
            field=models.CharField(default='HTG', max_length=10),
        ),
        migrations.AlterField(
            model_name='fundtransfer',
            name='method',
            field=models.CharField(choices=[('crypto', 'Crypto'), ('mobile', 'Mobile Money'), ('bank', 'Banque')], default='crypto', max_length=20),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='currency',
            field=models.CharField(default='HTG', max_length=10),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='method',
            field=models.CharField(choices=[('crypto', 'Crypto'), ('mobile', 'Mobile Money'), ('bank', 'Banque')], default='crypto', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='HTG', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('CREDIT', 'Crédit'), ('DEBIT', 'Débit')], default='CREDIT', max_length=30),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(default='HTG', max_length=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='network',
            field=models.CharField(choices=[('btc', 'Bitcoin'), ('eth', 'Ethereum'), ('bsc', 'Binance Smart Chain')], default='btc', max_length=50),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='public_key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(choices=[('crypto', 'Crypto'), ('mobile', 'Mobile Money'), ('bank', 'Banque')], default='crypto', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('user', 'network', 'public_key', 'address')},
        ),
    ]
