# Generated by Django 5.2.3 on 2026-02-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_wallet_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bonus_type',
            field=models.CharField(choices=[('signup', 'Création de compte'), ('referral', 'Parrainage'), ('payment_success', 'Paiement'), ('random', 'Aléatoire'), ('daily_login', 'Bonus quotidien'), ('contract', 'Contrat'), ('transfer', 'Transfert'), ('alert', 'Alerte'), ('reminder', 'Rappel')], default='signup', max_length=30),
        ),
    ]
