# Generated by Django 5.2.3 on 2026-02-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_transaction_bonus_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bonus_type',
            field=models.CharField(choices=[('signup', 'Création de compte'), ('referral', 'Parrainage'), ('payment_success', 'Paiement'), ('random', 'Aléatoire'), ('daily_login', 'Bonus quotidien'), ('contract', 'Contrat'), ('transfer', 'Transfert')], default='signup', max_length=30),
        ),
    ]
