# Generated by Django 5.2.3 on 2026-02-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_transaction_bonus_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancecurrency',
            name='currency',
            field=models.CharField(choices=[('jmu', 'JMU'), ('htg', 'HTG'), ('usd', 'USD')], default='jmu', max_length=10),
        ),
        migrations.AlterField(
            model_name='fundtransfer',
            name='currency',
            field=models.CharField(choices=[('jmu', 'JMU'), ('htg', 'HTG'), ('usd', 'USD')], default='jmu', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('jmu', 'JMU'), ('htg', 'HTG'), ('usd', 'USD')], default='jmu', max_length=10),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='currency',
            field=models.CharField(choices=[('jmu', 'JMU'), ('htg', 'HTG'), ('usd', 'USD')], default='jmu', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('jmu', 'JMU'), ('htg', 'HTG'), ('usd', 'USD')], default='jmu', max_length=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('jmu', 'JMU'), ('htg', 'HTG'), ('usd', 'USD')], default='jmu', max_length=10),
        ),
    ]
