# Generated by Django 5.2.3 on 2026-02-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_payment_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('CREDIT', 'ajoute'), ('DEBIT', 'retire')], default='CREDIT', max_length=30),
        ),
    ]
