# Generated by Django 5.2.3 on 2026-02-02 20:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Type métier',
                'verbose_name_plural': 'Types métiers',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Imèl')),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{8,15}$')], verbose_name='Telefòn')),
                ('role', models.CharField(choices=[('user', 'Senp Itilizatè'), ('dealer', 'Konsesyonè'), ('agency', 'Ajans Lokasyon'), ('garage', 'Garaj')], default='user', max_length=20)),
                ('user_type', models.CharField(choices=[('simple', 'Senp Itilizatè'), ('business', 'Biznis')], default='simple', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('invitation_code', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_failed_login', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('extra_roles', models.ManyToManyField(blank=True, related_name='users', to='users.usertype', verbose_name='Rôles métiers')),
            ],
            options={
                'verbose_name': 'Itilizatè',
                'verbose_name_plural': 'Itilizatè',
            },
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('avatar', models.ImageField(default=users.models.default_avatar, upload_to='avatars/')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('patente_number', models.CharField(blank=True, max_length=50, null=True)),
                ('patente_image', models.ImageField(blank=True, null=True, upload_to='patentes/')),
                ('web_site', models.URLField(blank=True, null=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='businessprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_type', models.CharField(choices=[('dd', 'Directeur Départemental'), ('rh', 'Ressources Humaines'), ('it', 'Département Informatique'), ('ac', 'Comptabilité'), ('mc', 'Mecanécanicien')], default='dd', max_length=20, verbose_name='Tip Anplwaye')),
                ('first_name', models.CharField(max_length=255, verbose_name='Non')),
                ('last_name', models.CharField(max_length=255, verbose_name='Siyati')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Imèl')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefòn')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adrès')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pòs')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dat')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='users.businessprofile', verbose_name='Biznis')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Anplwaye')),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_attempts', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(auto_now_add=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_successful', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Ordinateur'), ('tablet', 'Tablette'), ('unknown', 'Inconnu')], default='unknown', max_length=55)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SimpleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('avatar', models.ImageField(default=users.models.default_avatar, upload_to='avatars/')),
                ('address', models.TextField(blank=True, null=True)),
                ('driver_license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_license_image', models.ImageField(blank=True, null=True, upload_to='driver_licenses/')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simple', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Non')),
                ('last_name', models.CharField(max_length=50, verbose_name='Siyati')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Imèl')),
                ('phone', models.CharField(max_length=25, verbose_name='Telefòn')),
                ('driver_license_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nimewo Lisans')),
                ('business_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Non Biznis')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adrès')),
                ('patente_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nimewo Pantant')),
                ('web_site', models.URLField(blank=True, null=True, verbose_name='Sitwèb')),
                ('client_type', models.CharField(choices=[('user', 'Senp Itilizatè'), ('dealer', 'Konsesyonè'), ('agency', 'Ajans Lokasyon'), ('garage', 'Garaj')], default='user', max_length=20, verbose_name='Tip Kliyan')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dat')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL, verbose_name='Non')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Pwopriyetè')),
                ('real_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_client', to=settings.AUTH_USER_MODEL, verbose_name='Kliyan')),
                ('user_types', models.ManyToManyField(blank=True, to='users.usertype', verbose_name='Tip Metye')),
            ],
        ),
    ]
