# Generated by Django 5.2.3 on 2026-02-04 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='referrer',
            new_name='referrer_by',
        ),
    ]
