# Generated by Django 5.2.3 on 2026-02-04 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_referrer_customuser_referrer_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='referrer_by',
            new_name='referred_by',
        ),
    ]
