# Generated by Django 5.2.3 on 2026-02-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_referrer_by_customuser_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('dealer', 'Konsesyonè'), ('agency', 'Ajans Lokasyon'), ('garage', 'Garaj')], default='dealer', max_length=20),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='device_type',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Ordinateur'), ('tablet', 'Tablette'), ('unknown', 'Inconnu')], default='mobile', max_length=55),
        ),
    ]
