# Generated by Django 5.2.3 on 2026-02-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Jere Machin', max_length=255)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_update', models.DateField(auto_now=True)),
                ('last_change', models.DateField(blank=True, null=True)),
                ('version', models.CharField(default='Beta', max_length=50)),
                ('developer', models.CharField(default='Cobrapacedel™', max_length=100)),
                ('contact_email', models.EmailField(default='delinoiskadhaffimacarthur@gmail.com', max_length=254)),
            ],
            options={
                'verbose_name': 'Project Information',
                'verbose_name_plural': 'Project Information',
            },
        ),
    ]
