# Generated by Django 5.2.3 on 2026-02-05 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_initial'),
        ('users', '0003_rename_referrer_by_customuser_referred_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='created_by',
        ),
        migrations.AddField(
            model_name='contract',
            name='created_by_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_created_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_status',
            field=models.CharField(choices=[('pending', 'En cours'), ('drafted', 'En négociation'), ('completed', 'Complété'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Estati'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('sell', 'Vente'), ('rent', 'Location'), ('loan', 'Prêt'), ('service', 'Service')], default='sell', max_length=20, verbose_name='Tip Kontra'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_by_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_created_contract', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='warranty_period',
            field=models.PositiveIntegerField(blank=True, help_text='Durée de garantie', null=True, verbose_name='Garanti'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Deskripsyon'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tip Sèvis'),
        ),
    ]
