# Generated by Django 5.2.3 on 2026-02-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=255)),
                ('delete_reason', models.TextField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'deleted_fines',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='Montant appliqué au moment de l’infraction', max_digits=10, verbose_name='Pri')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('violation_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('penalty_applied_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, help_text='Observation ou note interne', null=True)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code unique de la violation', max_length=50, unique=True)),
                ('reason', models.CharField(help_text='Libellé de l’infraction', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('HTG', 'HTG'), ('USD', 'USD'), ('BTG', 'BTG')], max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
