# Generated by Django 5.1.6 on 2025-06-05 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fines', '0001_initial'),
        ('payments', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedfine',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_fines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deletedfine',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fine',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='finepay',
            name='fine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='fines.fine'),
        ),
        migrations.AddField(
            model_name='finepay',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='finepay',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fine_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finepay',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fine_vehicle', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='fine',
            name='violation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines', to='fines.violation'),
        ),
    ]
