# Generated by Django 5.2.3 on 2026-02-02 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fines', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedfine',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_fines_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deletedfine',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_fines_driven', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deletedfine',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_fines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fine',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Conducteur au moment de l’infraction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines_driven', to=settings.AUTH_USER_MODEL, verbose_name='Chofè'),
        ),
        migrations.AddField(
            model_name='fine',
            name='issuer',
            field=models.ForeignKey(blank=True, help_text='Agent ou autorité', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines_issued', to=settings.AUTH_USER_MODEL, verbose_name='Ajan Otorize'),
        ),
        migrations.AddField(
            model_name='fine',
            name='owner',
            field=models.ForeignKey(help_text='Propriétaire du véhicule', on_delete=django.db.models.deletion.CASCADE, related_name='fines_received', to=settings.AUTH_USER_MODEL, verbose_name='Pwopriyetè'),
        ),
        migrations.AddField(
            model_name='fine',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='vehicles.vehicle', verbose_name='Veyikil'),
        ),
        migrations.AddField(
            model_name='fine',
            name='violation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fines', to='fines.violation', verbose_name='Enfraksyon'),
        ),
    ]
