# Generated by Django 5.2.3 on 2026-02-05 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletedfine',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='deletedfine',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='base_amount',
        ),
        migrations.AddField(
            model_name='deletedfine',
            name='violation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_fines_violation', to='fines.violation'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='currency',
            field=models.CharField(choices=[('htg', 'HTG'), ('usd', 'USD'), ('jmu', 'JMU')], default='htg', max_length=5),
        ),
    ]
