# Generated by Django 5.1.6 on 2025-06-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('insurance', 'Assurance'), ('registration', 'Carte grise'), ('inspection', 'Contrôle technique')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('HTG', 'HTG'), ('USD', 'USD'), ('BTG', 'BTG'), ('BTC', 'BTC'), ('USDT', 'USDT')], max_length=5)),
                ('expiration_date', models.DateField()),
                ('renewed_at', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
