# Generated by Django 5.2.3 on 2026-02-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('insurance', 'Asirans'), ('registration', 'Kat Griz'), ('inspection', 'Kontwòl Teknik'), ('license', 'Lisans'), ('other', 'Lòt')], max_length=20, verbose_name='Tip Dokiman')),
                ('mandatory', models.BooleanField(default=False, verbose_name='Mandatè')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Fichye')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Dat Ekspirasyon')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Valid')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Payé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_expiry', models.DateField(verbose_name='Ancienne date d’expiration')),
                ('new_expiry', models.DateField(verbose_name='Nouvelle date d’expiration')),
                ('renewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Renouvellement de document',
                'verbose_name_plural': 'Renouvellements de documents',
                'ordering': ['-renewed_at'],
            },
        ),
    ]
