# Generated by Django 5.2.3 on 2026-02-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dokiman', 'verbose_name_plural': 'Dokiman'},
        ),
        migrations.AlterModelOptions(
            name='documentrenewal',
            options={'ordering': ['-renewed_at'], 'verbose_name': 'Renouvle Dokiman', 'verbose_name_plural': 'Renouvele Dikiman'},
        ),
        migrations.AddField(
            model_name='documentrenewal',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Peye'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('insurance', 'Asirans'), ('registration', 'Kat Griz'), ('license', 'Lisans'), ('other', 'Lòt')], default='license', max_length=20, verbose_name='Tip Dokiman'),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Peye'),
        ),
        migrations.AlterField(
            model_name='documentrenewal',
            name='new_expiry',
            field=models.DateField(verbose_name='Nouvo dat dekspirasyon'),
        ),
        migrations.AlterField(
            model_name='documentrenewal',
            name='old_expiry',
            field=models.DateField(verbose_name='Ansyen dat dekspirasyon'),
        ),
    ]
