# Generated by Django 5.1.6 on 2025-06-05 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Mécanicien',
                'verbose_name_plural': 'Mécaniciens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Locataire',
                'verbose_name_plural': 'Locataires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Vendeur',
                'verbose_name_plural': 'Vendeurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transferred_to',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Transféré à',
                'verbose_name_plural': 'Transféré à',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Machin'), ('motorcycle', 'Moto'), ('truck', 'Kamyon')], default='car', max_length=50, verbose_name='Type de Vehicule')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name="Numéro d'immatriculation")),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de série')),
                ('brand', models.CharField(max_length=50, verbose_name='Marque')),
                ('model', models.CharField(max_length=50, verbose_name='Modèle')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('color', models.CharField(max_length=30, verbose_name='Couleur')),
                ('mileage', models.PositiveIntegerField(default=0, verbose_name='Kilométrage')),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Essence'), ('diesel', 'Diesel'), ('electric', 'Électrique')], default='Essence', max_length=20, verbose_name='Type de carburant')),
                ('driver_license', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de permis de conduire')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('rented', 'Loué'), ('maintenance', 'En maintenance'), ('sold', 'Vendu'), ('transferred', 'Transféré')], default='available', max_length=20, verbose_name='Statut')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicle_images/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_mechanic', to='vehicles.mechanic', verbose_name='Mécanicien')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
                ('renter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_renter', to='vehicles.renter', verbose_name='Locataire')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_seller', to='vehicles.seller', verbose_name='Vendeur')),
                ('transferred_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_transferred_to', to='vehicles.transferred_to', verbose_name='Transféré à')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['-created_at'],
                'permissions': [('can_transfer_vehicle', 'Peut transférer un véhicule'), ('can_view_vehicle_history', "Peut voir l'historique des véhicules")],
            },
        ),
        migrations.CreateModel(
            name='VehicleTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_transfer_id', models.CharField(blank=True, max_length=6, verbose_name='ID du Transfert')),
                ('transfer_reason', models.TextField(blank=True, verbose_name='Raison du transfert')),
                ('transfer_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de transfert')),
                ('new_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to=settings.AUTH_USER_MODEL, verbose_name='Nouveau propriétaire')),
                ('previous_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to=settings.AUTH_USER_MODEL, verbose_name='Ancien propriétaire')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='vehicles.vehicle', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Transfert de véhicule',
                'verbose_name_plural': 'Transferts de véhicules',
                'ordering': ['-transfer_date'],
            },
        ),
    ]
