# Generated by Django 5.2.3 on 2026-02-02 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Voiture'), ('motorcycle', 'Moto'), ('truck', 'Camion'), ('bus', 'Bus')], default='car', max_length=50, verbose_name='Type de véhicule')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name="Numéro d'immatriculation")),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de série')),
                ('brand', models.CharField(max_length=50, verbose_name='Marque')),
                ('model', models.CharField(max_length=50, verbose_name='Modèle')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Couleur')),
                ('mileage', models.PositiveIntegerField(default=0, verbose_name='Kilométrage')),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Essence'), ('diesel', 'Diesel'), ('electric', 'Électrique'), ('hybrid', 'Hybride')], default='gasoline', max_length=20, verbose_name='Type de carburant')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('rentals', 'Loué'), ('maintenance', 'En maintenance'), ('contracts', 'Vendu'), ('loaned', 'Prêté')], default='available', max_length=20, verbose_name='Statut')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicle_images/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, limit_choices_to={'business_type': 'agency'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agencies_vehicles', to='users.businessprofile')),
                ('dealer', models.ForeignKey(blank=True, limit_choices_to={'business_type': 'dealer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealers_vehicles', to='users.businessprofile')),
                ('garage', models.ForeignKey(blank=True, limit_choices_to={'business_type': 'garage'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garages_vehicles', to='users.businessprofile')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ancien statut')),
                ('new_status', models.CharField(max_length=20, verbose_name='Nouveau statut')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de modification')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='vehicles.vehicle', verbose_name='Véhicule')),
            ],
        ),
    ]
