# Generated by Django 5.2.3 on 2026-02-05 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_referrer_by_customuser_referred_by'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='agency',
            field=models.ForeignKey(blank=True, limit_choices_to={'business_type': 'agency'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_vehicles', to='users.businessprofile'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='dealer',
            field=models.ForeignKey(blank=True, limit_choices_to={'business_type': 'dealer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealer_vehicles', to='users.businessprofile'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='garage',
            field=models.ForeignKey(blank=True, limit_choices_to={'business_type': 'garage'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garage_vehicles', to='users.businessprofile'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('rented', 'Loué'), ('sold', 'Vendu'), ('loaned', 'Prêté')], default='available', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='vehiclestatushistory',
            name='new_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nouveau statut'),
        ),
    ]
