# Generated by Django 5.2.3 on 2026-02-02 20:10

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('highway_name', models.CharField(blank=True, max_length=150)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(choices=[('HTG', 'HTG'), ('USD', 'USD'), ('EUR', 'EUR')], default='HTG', max_length=5)),
            ],
            options={
                'verbose_name': 'Poste de péage',
                'verbose_name_plural': 'Postes de péage',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TollBooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('passage_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_paid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Guichet de péage',
                'verbose_name_plural': 'Guichets de péage',
                'ordering': ['-passage_date'],
            },
        ),
        migrations.CreateModel(
            name='TollDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0.03'), help_text='Taux mensuel', max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_fully_paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TollDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
