# Generated by Django 5.1.6 on 2025-06-05 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('highway_name', models.CharField(blank=True, max_length=150)),
                ('region', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Poste de péage',
                'verbose_name_plural': 'Postes de péage',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TollDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interest_applied', models.BooleanField(default=False)),
                ('remaining_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_fully_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TollDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=15)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TollPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('HTG', 'Gourde'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='HTG', max_length=3)),
                ('payment_method', models.CharField(choices=[('cash', 'Espès'), ('card', 'Kat'), ('mobile', 'Mobil')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('completed', 'Complété'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paiement de péage',
                'verbose_name_plural': 'Paiements de péage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TollTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Succès'), ('failed', 'Échec'), ('refunded', 'Remboursé'), ('error', 'Erreur technique')], max_length=20)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Transaction de péage',
                'verbose_name_plural': 'Transactions de péage',
                'ordering': ['-confirmed_at'],
            },
        ),
        migrations.CreateModel(
            name='TollBooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('toll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booths', to='tolls.toll')),
            ],
            options={
                'verbose_name': 'Guichet de péage',
                'verbose_name_plural': 'Guichets de péage',
                'ordering': ['toll__name', 'booth_number'],
            },
        ),
    ]
