# Generated by Django 5.1.6 on 2025-06-05 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tolls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tolldebt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tolldetection',
            name='booth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tolls.tollbooth'),
        ),
        migrations.AddField(
            model_name='tollpayment',
            name='toll_booth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='tolls.tollbooth'),
        ),
        migrations.AddField(
            model_name='tollpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toll_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tolltransaction',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='tolls.tollpayment'),
        ),
        migrations.AlterUniqueTogether(
            name='tollbooth',
            unique_together={('toll', 'booth_number')},
        ),
    ]
