# Generated by Django 5.2.3 on 2026-02-02 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tolls', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tollbooth',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_tolls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tollbooth',
            name='toll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booths', to='tolls.toll'),
        ),
        migrations.AddField(
            model_name='tollbooth',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toll_passages', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='tolldebt',
            name='booth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='tolls.tollbooth'),
        ),
        migrations.AddField(
            model_name='tolldebt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toll_debts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tolldetection',
            name='booth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='tolls.tollbooth'),
        ),
        migrations.AlterUniqueTogether(
            name='tollbooth',
            unique_together={('toll', 'booth_number')},
        ),
    ]
