# Generated by Django 5.2.3 on 2026-02-05 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolls', '0002_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toll',
            options={'ordering': ['name'], 'verbose_name': 'Rout Pòs Peyaj', 'verbose_name_plural': 'Rout Pòs Peyaj'},
        ),
        migrations.RenameField(
            model_name='tolldebt',
            old_name='user',
            new_name='driver',
        ),
        migrations.RemoveField(
            model_name='tollbooth',
            name='location',
        ),
        migrations.RemoveField(
            model_name='tolldetection',
            name='plate_number',
        ),
        migrations.AddField(
            model_name='tolldetection',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='toll',
            name='currency',
            field=models.CharField(choices=[('htg', 'HTG'), ('usd', 'USD'), ('jmu', 'JMU')], default='htg', max_length=5),
        ),
        migrations.AlterField(
            model_name='tollbooth',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_tolls', to='vehicles.vehicle'),
        ),
    ]
