# Generated by Django 5.2.3 on 2026-02-02 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('payments', '0001_initial'),
        ('tolls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='toll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tolls.toll'),
        ),
        migrations.AddField(
            model_name='notification',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.transaction'),
        ),
    ]
