# Generated by Django 5.1.6 on 2025-06-05 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('payments', '0001_initial'),
        ('tolls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='toll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tolls', to='tolls.toll'),
        ),
        migrations.AddField(
            model_name='notification',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='payments.transaction'),
        ),
    ]
