# Generated by Django 5.2.3 on 2026-02-05 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_remove_contract_created_by_contract_created_by_owner_and_more'),
        ('documents', '0003_alter_document_options_alter_documentrenewal_options_and_more'),
        ('fines', '0003_remove_deletedfine_amount_remove_deletedfine_reason_and_more'),
        ('notifications', '0003_initial'),
        ('payments', '0006_alter_transaction_bonus_type'),
        ('tolls', '0002_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notifikasyon', 'verbose_name_plural': 'Notifikasyon'},
        ),
        migrations.AddField(
            model_name='notification',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dat'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='documents.documentrenewal'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='fine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='fines.fine'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Li'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Mesaj'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('danger', 'Danger'), ('signup', 'Nouvel utilisateur'), ('payment', 'Paiement'), ('contract', 'Contrat'), ('alert', 'Alerte'), ('reminder', 'Rappel'), ('bonus', 'Bonus'), ('referral', 'Parrainage')], default='alert', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tit'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='toll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tolls.toll'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='payments.transaction'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='vehicles.vehicle'),
        ),
    ]
