# Generated by Django 5.2.3 on 2026-02-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_options_notification_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Infòmasyon'), ('success', 'Reyisi'), ('warning', 'Avètisman'), ('danger', 'Danje'), ('signup', 'Nouvo Itilizatè'), ('payment', 'Pèman'), ('contract', 'Kontra'), ('alert', 'Alèt'), ('reminder', 'Rappel'), ('bonus', 'Bonis'), ('referral', 'Parenn')], default='alert', max_length=50),
        ),
    ]
